# Generated by Django 5.1.15 on 2026-07-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
