# Generated by Django 5.1.15 on 2026-07-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_rename_phone_number_patient_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
